DROP DATABASE IF EXISTS DB_2_3_AS_QS;
CREATE DATABASE DB_2_3_AS_QS;
USE DB_2_3_AS_QS;
DROP TABLE IF EXISTS Department2;
CREATE TABLE Department2(
	DepartmentID 			TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DepartmentName 			NVARCHAR(20) NOT NULL
);
DROP TABLE IF EXISTS Position2;
CREATE TABLE Position2(
	PositionID				TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PositionName			ENUM("Dev","Test","Scrum Master","PM") NOT NULL
);
DROP TABLE IF EXISTS Account2;
CREATE TABLE Account2(
	AccountID				TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Email					VARCHAR(50) NOT NULL,
    Username				VARCHAR(50) NOT NULL,
    FullName				VARCHAR(50) NOT NULL,
    DepartmentID 			TINYINT UNSIGNED NOT NULL,
    PositionID				TINYINT UNSIGNED NOT NULL,
    CreateDate				DATE DEFAULT NOW() NOT NULL,
    FOREIGN KEY(DepartmentID) REFERENCES Department2(DepartmentID),
    FOREIGN KEY(DepartmentID) REFERENCES Department2(DepartmentID)
);
DROP TABLE IF EXISTS Group2;
CREATE TABLE Group2(
	GroupID					TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    GroupName				NVARCHAR(50) NOT NULL,
    CreatorID				TINYINT UNSIGNED NOT NULL,
    CreateDate				DATE DEFAULT NOW() NOT NULL
);
DROP TABLE IF EXISTS GroupAccount2;
CREATE TABLE GroupAccount2(
	GroupID					TINYINT UNSIGNED AUTO_INCREMENT,
    AccountID				NVARCHAR(50) NOT NULL,
    PRIMARY KEY (GroupID,AccountID),
    JoinDate				DATE DEFAULT NOW() NOT NULL,
    FOREIGN KEY(AccountID) 	REFERENCES Account2(AccountID)
);
DROP TABLE IF EXISTS TypeQuestion2;
CREATE TABLE TypeQuestion2 (
    TypeID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TypeName ENUM("Esay","Multiple-Choice") NOT NULL
);
DROP TABLE IF EXISTS CategoryQuestion2;
CREATE TABLE CategoryQuestion(
    CategoryID				TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CategoryName			NVARCHAR(50) NOT NULL
);
DROP TABLE IF EXISTS Question2;
CREATE TABLE Question2(
    QuestionID				TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Content					NVARCHAR(50),
    CategoryID				TINYINT UNSIGNED,
    TypeID					TINYINT UNSIGNED,
    CreatorID				TINYINT UNSIGNED,
    CreateDate				DATE DEFAULT NOW()
);
DROP TABLE IF EXISTS Answer2;
CREATE TABLE Answer2(
    Answers					TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Content					NVARCHAR(50),
    QuestionID				TINYINT UNSIGNED,
    isCorrect				BIT
);
DROP TABLE IF EXISTS Exam2;
CREATE TABLE Exam2(
    ExamID					TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Code					VARCHAR(10),
    Title					NVARCHAR(50),
    CategoryID				TINYINT UNSIGNED,
    Duration				TINYINT UNSIGNED,
    CreatorID				TINYINT UNSIGNED,
    CreateDate				DATE DEFAULT NOW()
);
DROP TABLE IF EXISTS ExamQuestion2;
CREATE TABLE ExamQuestion2(
    ExamID				TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	QuestionID			TINYINT UNSIGNED
);







